#!/bin/bash

FC = mpifort

FCFLAGS = -Wall -Wextra
FLPATH = -L../C -L../../
FIPATH = -I../C -I../../
FLAB = -lmuiCouplingMethodsCAPI
LDFLAGS = -lstdc++


default: cs_MUI_CU_FR.o cs_MUI_CU_AK.o cs_MUI_CU_IQNILS.o
	ar rcs libmuiCouplingMethodsFAPI.a cs_MUI_CU_FR.o cs_MUI_CU_AK.o cs_MUI_CU_IQNILS.o

%.o : %.f90
	${FC} ${FCFLAGS} -c $< -o $@ ${FLPATH} ${FLAB} ${LDFLAGS}

.PHONY : clean

clean :
	${RM} -rf *.o *.mod *.a
