#!/bin/bash

CXX = cc

CCFLAGS = -Wall -Wextra
CICODEPATH = -I../../
CIEIGENPATH = -I/work/c01/c01/wendiliu/app/FEniCS/V2019.1.0/eigen-3.3.9/
CIMUIPATH = -I/work/c01/c01/wendiliu/app/MUI/MUI-1.1/wrappers/C -I/work/c01/c01/wendiliu/app/MUI/MUI-1.1
CLPATH = -L/work/c01/c01/wendiliu/app/MUI/MUI-1.1 -L/work/c01/c01/wendiliu/app/MUI/MUI-1.1/wrappers/C
CLNAME = -lwrapperC 
LDFLAGS = -lstdc++


default: fixedRelaxation_CAPI.o aitken_CAPI.o iqnils_CAPI.o
	ar rcs libmuiCouplingMethodsCAPI.a fixedRelaxation_CAPI.o aitken_CAPI.o iqnils_CAPI.o

%.o : %.cpp
	${CXX} ${CCFLAGS} -c $^ -o $@ ${CICODEPATH} ${CIEIGENPATH} ${CIMUIPATH} ${CLPATH} ${CLNAME} ${LDFLAGS}

.PHONY : clean

clean :
	${RM} -rf *.o *.a
